name: DiscordDeathMessages
version: 1.0.0
author: Romejanic
api-version: 1.16

main: com.romejanic.ddm.DiscordDeathMessages

commands:
    ddmset:
        description: Set the Webhook URL for messages
        usage: /ddmset <url>
    ddmclear:
        description: Clears the Webhook URL for messages
        usage: /ddmclear
    ddmcolor:
        description: Sets the accent color for your death messages
        usage: /ddmcolor <hex color|clear>
        aliases: [ ddmcolour ]
    ddmmotto:
        description: Sets the motto text for your death messages
        usage: /ddmmotto <message|clear>